sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

install:
  - cd frontend
  - yarn install

script:
  - yarn run build
  - cd ..
  - cd server
  - docker run -v `pwd`:/go/src/server -w /go/src/server golang:1.8-alpine go get -v ./... && go build -v
  - cd ..
  - docker build -t keetraxx/nyaago .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push keetraxx/nyaago
