sudo: required

language: generic

services:
  - docker

before_install:
  - ~/.nvm/nvm.sh
  - nvm install --lts

script:
  - cd frontend
  - yarn install
  - yarn run build
  - cd ..
  - cd server
  - docker run -v `pwd`:/app golang:1.8-alpine go-wrapper get -v ./... && go-wrapper build
  - cd ..
  - docker build -t keetraxx/nyaago .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push keetraxx/nyaago
